---
exp_name: SphereNet # 0417
exp_dir: ../exp
use_gpu: True
device: 0
seed: None # If you want to reproduce set the seed
model_name: SphereNet
train_resume: False

train:
    optimizer: Adam
    epoch: 150
    loss_function : MAE
    lr: 1.0e-3
    wd: 0.0e-4 # Adam
    momentum: 0.9 # SGD
    T_0: 50 # cosine annealing
    T_mult: 5 # cosine annealing
    batch_size : 64

model:
    mol_state: g
    num_layers: 4
    hidden_channels: 128
    out_channels: 1
    int_emb_size: 64
    basis_emb_size_dist: 8
    basis_emb_size_angle: 8
    basis_emb_size_torsion: 8
    out_emb_channels: 256
    num_spherical: 7
    num_radial: 6
    envelope_exponent: 5
    num_before_skip: 1
    num_after_skip: 2
    num_output_layers: 3
    output_init: GlorotOrthogonal
    use_node_features: True
    cutoff: 5.0
    energy_and_force: False