---
exp_name: ComENet_g # 0417
exp_dir: ../exp
use_gpu: True
device: 0
seed: None # If you want to reproduce set the seed
model_name: ComENet
train_resume: False

train:
    optimizer: Adam
    epoch: 150
    loss_function : MAE
    lr: 1.0e-3
    wd: 0.0e-4 # Adam
    momentum: 0.9 # SGD
    T_0: 50 # cosine annealing
    T_mult: 5 # cosine annealing
    batch_size : 64

model:
    mol_state: g
    cutoff: 8.0
    num_layers: 4
    hidden_channels: 256
    middle_channels: 64
    out_channels: 1
    num_radial: 3
    num_spherical: 2
    num_output_layers: 3